Algoritmo "5imparesnaturais"
// Disciplina   :  [Agoritmo]
// Professor   : Arnobio
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Luan Silvestre
// Data atual  : 10/09/2019
Var
// Seção de Declarações das variáveis
x:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Programa cinco números impares naturais")
X<-0
para x de 1 ate 9 passo 2 faca
escreval("número =",x)
fimpara

Fimalgoritmo