Algoritmo "lacopara1"
// Disciplina   :  [algoritmo]
// Professor   : Arnobio
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Luan Silvestre
// Data atual  : 03/09/2019
Var
// Seção de Declarações das variáveis
conta:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("programa exibe números de 0 a 9")
conta<-0
para conta de 1 ate 9 faca
escreval("conta=",conta)
fimpara
Fimalgoritmo