Algoritmo "lacopara2"
// Disciplina   :  [algoritmo]
// Professor   : Arnobio
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Luan Silvestre
// Data atual  : 03/09/2019
Var
// Seção de Declarações das variáveis 
conta:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("programa exibe os números de 9 a 1")
conta<-9
para conta de 9 ate 1 passo -1 faca
escreval("conta=",conta)
fimpara
Fimalgoritmo