Algoritmo "lacopara3"
// Disciplina   :  [algoritmo]
// Professor   : Arnobio
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Luan Silvestre
// Data atual  : 03/09/2019
Var
// Seção de Declarações das variáveis 
conta:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("progama exibe números de 0 a 9,de 3 em 3")
conta<-0
para conta de 0 ate 9 passo 3 faca
escreval("conta=",conta)
fimpara
Fimalgoritmo