Algoritmo "programasoma"
// Disciplina   :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : este programa soma as variáveis(função)
// Autor(a)    : Luan Silvestre
// Data atual  : 06/08/2019
Var
a,b,r:inteiro

Inicio
a<-10
b<-5
escreval("programa de soma")
escreval("o valor de A é de:",a)
escreval("o valor de b é de;",b)
r<-a+b

escreval("a soma de A e B:",r)
Fimalgoritmo