Algoritmo "ProgramaSubtração"
// Disciplina   :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Luan Silvestre
// Data atual  : 06/08/2019
Var
a,b,r:inteiro

Inicio
a<-10
b<-5
escreval("Programa de Subtração")
escreval("o valor de A:",a)
escreval("o valor de B:",b)
r<-a-b

escreval("a subtração de A e B:",r)
Fimalgoritmo