Algoritmo "programasoma"
// Disciplina   :  [Algorítimo]
// Professor   : Arnobio
// Descrição   : este programa soma as variáveis a e b indicadas pelo usuário.
// Autor(a)    : Luan Silvestre
// Data atual  : 13/08/2019
Var
a,b,r:inteiro

Inicio
escreval("programa da soma")
escreval("o valor de a é:")
leia(a)
escreval("o valor de b é:")
leia(b)
r<-(a+b)
escreval("a soma de a e b é:",r)

Fimalgoritmo