Algoritmo "tabuada6"
// Disciplina   :  [Algoritmo]
// Professor   : Arnobio
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Luan Silvestre
// Data atual  : 10/09/2019
Var
// Seção de Declarações das variáveis 
x,r:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Programa tabuada do seis")
x<-0
para x de 0 ate 10 faca
r<-x*6
escreval("6 x",X,"=",r)
fimpara

Fimalgoritmo